// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "BIT101Modules",
    platforms: [.iOS(.v17), .watchOS(.v10), .macOS(.v14)],
    products: [
        .library(name: "ScoreDomain", targets: ["ScoreDomain"]),
        .library(name: "SchedulePorts", targets: ["SchedulePorts"]),
        .library(name: "ScheduleFeature", targets: ["ScheduleFeature"]),
        .library(name: "GalleryFeature", targets: ["GalleryFeature"]),
        .library(name: "CourseFeature", targets: ["CourseFeature"]),
        .library(name: "PaperFeature", targets: ["PaperFeature"]),
        .library(name: "MineFeature", targets: ["MineFeature"]),
        .library(name: "CommunityUI", targets: ["CommunityUI"]),
        .library(name: "MediaKit", targets: ["MediaKit"]),
        .library(name: "ScoreFeature", targets: ["ScoreFeature"]),
        .library(name: "ScoreInfrastructure", targets: ["ScoreInfrastructure"]),
        .library(name: "MapFeature", targets: ["MapFeature"]),
        .library(name: "ScheduleDomain", targets: ["ScheduleDomain"]),
        .library(name: "ScheduleSync", targets: ["ScheduleSync"]),
        .library(name: "SchedulePersistence", targets: ["SchedulePersistence"]),
        .library(name: "ScheduleInfrastructure", targets: ["ScheduleInfrastructure"]),
        .library(name: "CommunityCore", targets: ["CommunityCore"]),
        .library(name: "CommunityPersistence", targets: ["CommunityPersistence"]),
        .library(name: "DesignSystemKit", targets: ["DesignSystemKit"]),
        .library(name: "ClientCore", targets: ["ClientCore"]),
        .library(name: "StorageCore", targets: ["StorageCore"]),
        .library(name: "TransportCore", targets: ["TransportCore"]),
        .library(name: "CommunityTransport", targets: ["CommunityTransport"]),
        .library(name: "ScheduleActivityContracts", targets: ["ScheduleActivityContracts"]),
        .library(name: "ScheduleContracts", targets: ["ScheduleContracts"]),
        .library(name: "ScheduleSharedStore", targets: ["ScheduleSharedStore"]),
    ],
    targets: [
        .target(name: "SchedulePorts", dependencies: ["ClientCore", "ScheduleDomain", "StorageCore"], path: "Modules/SchedulePorts/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScoreDomain", dependencies: ["ClientCore", "StorageCore"], path: "Modules/ScoreDomain/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleFeature", dependencies: ["SchedulePorts", "ClientCore", "DesignSystemKit", "ScheduleDomain", "ScheduleContracts", "StorageCore", "TransportCore"], path: "Modules/ScheduleFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(
            name: "GalleryFeature",
            dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"],
            path: "Modules/GalleryFeature/Sources",
            swiftSettings: [.defaultIsolation(MainActor.self)]
        ),
        .target(name: "CourseFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"], path: "Modules/CourseFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "PaperFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"], path: "Modules/PaperFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "MineFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"], path: "Modules/MineFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityUI", dependencies: ["CommunityCore", "DesignSystemKit", "MediaKit"], path: "Modules/CommunityUI/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "MediaKit", dependencies: ["DesignSystemKit", "StorageCore", "TransportCore"], path: "Modules/MediaKit/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScoreInfrastructure", dependencies: ["ClientCore", "ScoreDomain", "StorageCore", "TransportCore"], path: "Modules/ScoreInfrastructure/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScoreFeature", dependencies: ["ScoreDomain", "ClientCore", "DesignSystemKit", "MediaKit", "StorageCore", "TransportCore"], path: "Modules/ScoreFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "MapFeature", dependencies: ["DesignSystemKit", "ScheduleContracts", "TransportCore"], path: "Modules/MapFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleSync", dependencies: ["ScheduleDomain", "StorageCore"], path: "Modules/ScheduleSync/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "SchedulePersistence", dependencies: ["ScheduleDomain", "StorageCore"], path: "Modules/SchedulePersistence/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleDomain", dependencies: ["ScheduleContracts"], path: "Modules/ScheduleDomain/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleInfrastructure", dependencies: ["SchedulePorts", "ClientCore", "ScheduleDomain", "TransportCore"], path: "Modules/ScheduleInfrastructure/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityPersistence", dependencies: ["CommunityCore", "StorageCore"], path: "Modules/CommunityPersistence/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityCore", dependencies: ["StorageCore"], path: "Modules/CommunityCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "DesignSystemKit", path: "Modules/DesignSystemKit/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ClientCore", path: "Modules/ClientCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "StorageCore", path: "Modules/StorageCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "TransportCore", path: "Modules/TransportCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityTransport", dependencies: ["TransportCore"], path: "Modules/CommunityTransport/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleActivityContracts", path: "Modules/ScheduleActivityContracts/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleContracts", path: "Modules/ScheduleContracts/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleSharedStore", dependencies: ["ScheduleContracts", "StorageCore"], path: "Modules/ScheduleSharedStore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "BIT101TestSupport", dependencies: ["StorageCore"], path: "ModuleTests/Support", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "TransportModuleTests", dependencies: ["ClientCore", "CommunityTransport", "ScheduleDomain", "ScheduleFeature", "ScheduleInfrastructure", "SchedulePorts", "StorageCore", "TransportCore"], path: "ModuleTests/Transport", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "CommunityModuleTests", dependencies: ["BIT101TestSupport", "CommunityCore", "CommunityPersistence", "CommunityTransport", "CommunityUI", "CourseFeature", "DesignSystemKit", "GalleryFeature", "MediaKit", "MineFeature", "PaperFeature", "StorageCore", "TransportCore"], path: "ModuleTests/Community", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "ScheduleModuleTests", dependencies: ["BIT101TestSupport", "ClientCore", "ScheduleDomain", "ScheduleFeature", "SchedulePersistence", "SchedulePorts", "StorageCore"], path: "ModuleTests/Schedule", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "ContractsModuleTests", dependencies: ["BIT101TestSupport", "ScheduleContracts", "ScheduleDomain", "ScheduleSharedStore", "StorageCore"], path: "ModuleTests/Contracts", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "ScoreModuleTests", dependencies: ["BIT101TestSupport", "ClientCore", "CommunityCore", "DesignSystemKit", "ScoreDomain", "ScoreFeature", "ScoreInfrastructure", "StorageCore", "TransportCore"], path: "ModuleTests/Score", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "MapModuleTests", dependencies: ["MapFeature"], path: "ModuleTests/Map", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "SyncModuleTests", dependencies: ["ScheduleDomain", "ScheduleSync", "StorageCore"], path: "ModuleTests/Sync", swiftSettings: [.defaultIsolation(MainActor.self)]),
    ]
)
