// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "BIT101Modules",
    platforms: [.iOS(.v17), .watchOS(.v10), .macOS(.v14)],
    products: [
        .library(name: "ScheduleFeature", targets: ["ScheduleFeature"]),
        .library(name: "GalleryFeature", targets: ["GalleryFeature"]),
        .library(name: "CourseFeature", targets: ["CourseFeature"]),
        .library(name: "PaperFeature", targets: ["PaperFeature"]),
        .library(name: "MineFeature", targets: ["MineFeature"]),
        .library(name: "CommunityUI", targets: ["CommunityUI"]),
        .library(name: "MediaKit", targets: ["MediaKit"]),
        .library(name: "ScoreFeature", targets: ["ScoreFeature"]),
        .library(name: "MapFeature", targets: ["MapFeature"]),
        .library(name: "ScheduleDomain", targets: ["ScheduleDomain"]),
        .library(name: "ScheduleInfrastructure", targets: ["ScheduleInfrastructure"]),
        .library(name: "CommunityCore", targets: ["CommunityCore"]),
        .library(name: "DesignSystemKit", targets: ["DesignSystemKit"]),
        .library(name: "ClientCore", targets: ["ClientCore"]),
        .library(name: "StorageCore", targets: ["StorageCore"]),
        .library(name: "TransportCore", targets: ["TransportCore"]),
        .library(name: "CommunityTransport", targets: ["CommunityTransport"]),
        .library(name: "ScheduleContracts", targets: ["ScheduleContracts"]),
        .library(name: "ScheduleSharedStore", targets: ["ScheduleSharedStore"]),
    ],
    targets: [
        .target(name: "ScheduleFeature", dependencies: ["ClientCore", "DesignSystemKit", "ScheduleDomain", "ScheduleContracts", "StorageCore", "TransportCore"], path: "Modules/ScheduleFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "GalleryFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "StorageCore", "TransportCore"], path: "Modules/GalleryFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CourseFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"], path: "Modules/CourseFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "PaperFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"], path: "Modules/PaperFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "MineFeature", dependencies: ["CommunityCore", "CommunityTransport", "CommunityUI", "DesignSystemKit", "MediaKit", "TransportCore"], path: "Modules/MineFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityUI", dependencies: ["CommunityCore", "DesignSystemKit", "MediaKit"], path: "Modules/CommunityUI/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "MediaKit", dependencies: ["DesignSystemKit", "StorageCore", "TransportCore"], path: "Modules/MediaKit/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScoreFeature", dependencies: ["ClientCore", "DesignSystemKit", "StorageCore", "TransportCore"], path: "Modules/ScoreFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "MapFeature", dependencies: ["DesignSystemKit", "ScheduleContracts"], path: "Modules/MapFeature/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleDomain", dependencies: ["ClientCore", "ScheduleContracts", "StorageCore"], path: "Modules/ScheduleDomain/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleInfrastructure", dependencies: ["ClientCore", "ScheduleDomain", "TransportCore"], path: "Modules/ScheduleInfrastructure/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityCore", path: "Modules/CommunityCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "DesignSystemKit", path: "Modules/DesignSystemKit/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ClientCore", path: "Modules/ClientCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "StorageCore", path: "Modules/StorageCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "TransportCore", path: "Modules/TransportCore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "CommunityTransport", dependencies: ["TransportCore"], path: "Modules/CommunityTransport/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleContracts", path: "Modules/ScheduleContracts/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .target(name: "ScheduleSharedStore", dependencies: ["ScheduleContracts", "StorageCore"], path: "Modules/ScheduleSharedStore/Sources", swiftSettings: [.defaultIsolation(MainActor.self)]),
        .testTarget(name: "BIT101ModulesTests", dependencies: ["MediaKit", "CommunityUI", "DesignSystemKit", "ClientCore", "CommunityCore", "CommunityTransport", "ScheduleContracts", "ScheduleSharedStore", "ScheduleInfrastructure", "ScheduleDomain", "ScheduleFeature", "GalleryFeature", "CourseFeature", "PaperFeature", "MineFeature", "ScoreFeature", "StorageCore", "TransportCore"], path: "ModuleTests", swiftSettings: [.defaultIsolation(MainActor.self)]),
    ]
)
